# Generated by Django 3.2 on 2021-05-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_authorities_health_healthservices_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='neighborhood',
        ),
    ]
