# Generated by Django 3.2.1 on 2021-05-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_profile_neighborhood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
